version: "3"
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:8080"
  
  
volumes:
  postgres_data: